### ISSUE TITLE
Unexpected text auto-wrapping causing highlight brackets to be off by 1 line.

### ISSUE THREAD

**Issue by hunterhector** [asyml/stave#53]
There are several UI glitches that could be caused by similar calculation errors, see the following screenshots and description

![image](https://user-images.githubusercontent.com/1015991/79592179-9ff8d500-80a7-11ea-8def-c24b4ad9416c.png)

This screenshot shows that some sentences are longer than the screen is automatically wrapped (see the "before" and "face" word). These are probably unexpected, and it seems that the annotation highlight positions after such wrappings are off by a little, see the following image:

![image](https://user-images.githubusercontent.com/1015991/79592330-d9c9db80-80a7-11ea-88b1-5d1c2d1fea9d.png)

Note that after the first auto-wrap "was", the highlighting is off by 1 line, and after the second auto-wrap "calmness", the highlight is off by 2 lines.

**Comment by GingerBear** [comment]
I see this issue only when I resize the browser for a second, then the issue disappear. Is that the case for you?

**Comment by hunterhector** [comment]
I have tried it on chrome, firefox and safari, observed similar problems. The visual offsets are slightly different, but seems all related to text autowrap.

I noticed the highlights will keep un-changed for a few seconds after resizing, but even after that, the offset is still wrong.

**Comment by GingerBear** [comment]
interesting, will test this in other browser

**Comment by hunterhector** [comment]
Previously caused by scroll bar issues and resolved in https://github.com/asyml/stave/pull/72
