### ISSUE TITLE
Occasional annotation highlight missmatching.

### ISSUE THREAD

**Issue by hunterhector** [asyml/stave#74]
With a recent bug fix, the annotation highlighting problem disappear in most scenarios. But there are still some funny annotation mismatch problems.

The problem seems harder to reproduce, I have attached one specific datapack/ontology pair that creates this. To reproduce, select this document, and select the `WikiSection` box, resize the browser window and try out, you may be able to observe the phenomenon like the following screenshot:

![Screen Shot 2020-06-12 at 11 46 29 PM](https://user-images.githubusercontent.com/1015991/84559267-119b7b00-ad07-11ea-949d-9ceca0313831.png)

There are two interesting things here:
1. Some annotations are off by a couple of lines.
2. There are funny small shapes as pointed by the arrows, those should not happen because the whole green area is the same annotation (WikiSection)

**Comment by hunterhector** [comment]
The following gist can be used to reproduce the above screenshot

https://gist.github.com/hunterhector/9458ce873d886f0b915bd0ea15231e57

**Comment by GingerBear** [comment]
I am able to reproduce, I am taking a look

**Comment by hunterhector** [comment]
![Screen Shot 2020-06-18 at 11 35 04 AM](https://user-images.githubusercontent.com/1015991/85041385-db6f5880-b157-11ea-852c-667a7923d9e1.png)

The problem still exists. It can be reproduced by using the document `abc_0009` in the example database. Select the legend `Document`, resizing the window a bit and then you can see the mismatching. This may also be related to https://github.com/asyml/stave/issues/79

**Comment by hunterhector** [comment]
Closed since cannot reproduce at the current version.
